batch_size: 16
max_length: 512
train_args:
  evaluation_strategy: epoch
  learning_rate: 2e-5
  per_device_train_batch_size: ${..batch_size}
  per_device_eval_batch_size: ${..batch_size}
  weight_decay: 0.01
  save_total_limit: 3
  num_train_epochs: 4
  predict_with_generate: true